#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform Camera
{
	vec3 pos;
	mat4 view;
	mat4 proj;
} camera;
layout(set = 1, binding = 0) uniform Atmosphere
{
	vec4 sun; // dir, illuminance
	int steps;
} atmosphere;
layout(set = 1, binding = 1, rgba16f) uniform writeonly image2D outImage;
layout(set = 1, binding = 2) uniform sampler2D depth;

vec3 PixelToViewPos(ivec2 pixel, ivec2 size)
{
	vec2 uv = (vec2(pixel) + 0.5) / vec2(size);
	uv.y = 1.0 - uv.y;
	
	float z = texture(depth, uv).r;
	
	vec3 ndc = vec3(uv * 2.0 - 1.0, z);
	vec4 viewPos = inverse(camera.proj) * vec4(ndc, 1.0);
	viewPos /= viewPos.w;
	return viewPos.xyz;
}

vec3 rayleighScattering(float y)
{
	const vec3 rayleigh = vec3(5.802, 13.558, 33.1) * 1e-6;
	return rayleigh * exp(-y / 8000.0);
}

vec3 mieScattering(float y)
{
	const vec3 mie = vec3(3.996, 3.996, 3.996) * 1e-6;
	return mie * exp(-y / 1200.0);
}

vec3 ScatteringCoefficient(float y)
{
	vec3 sigma = rayleighScattering(y) + mieScattering(y);
	return sigma;
}

vec3 AbsorptionCoefficient(float y)
{
	const vec3 mie = vec3(4.4, 4.4, 4.4) * 1e-6;
	const vec3 ozone = vec3(0.65, 1.881, 0.085) * 1e-6;
	return mie * exp(-y / 1200.0) + ozone * max(0.0, 1.0 - abs(y - 25000.0) / 15000.0);
}

float RayleighPhase(float mu)
{
	return 3 * (1 + mu * mu) / (16 * 3.141592);
}

float MiePhase(float mu, float g)
{
	return 3 * (1 - g * g) * (1 + mu * mu) / (8 * 3.141592 * (2 + g * g) * pow(1 + g * g - 2 * g * mu, 3.0/2.0));
}

bool RaySphereIntersect(vec3 rayOrigin, vec3 rayDir, vec3 sphereOrigin, float radius, out float near, out float far)
{
	vec3 rs = sphereOrigin - rayOrigin;
	float a2 = dot(rs, rs);
	float b = dot(rs, rayDir);
	float c2 = a2 - b * b;
	float r2 = radius * radius;
	if (c2 > r2)
		return false;
	
	float d = sqrt(r2 - c2); // 구 내부 ray길이
	near = b - d;
	far = b + d;
	
	return far >= 0.0;
}

void main()
{
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(outImage);
	if (pixel.x >= size.x || pixel.y >= size.y)
		return;
	
	const vec3 sunDir = atmosphere.sun.xyz;
	const vec3 viewPos = PixelToViewPos(pixel, size);
	const vec3 worldPos = (inverse(camera.view) * vec4(viewPos, 1.0)).xyz;
	const vec3 rayDir = normalize(worldPos - camera.pos);
	
	const float groundRadius = 6360 * 1000.0;
	const float atmosphereRadius = 6460 * 1000.0;
	const vec3 planetCenter = vec3(0.0, -groundRadius, 0.0);
	
	float nearAtmo = 0.0;
	float farAtmo = 1.0;
	if (!RaySphereIntersect(camera.pos, rayDir, planetCenter, atmosphereRadius, nearAtmo, farAtmo))
	{
		imageStore(outImage, pixel, vec4(0, 0, 0, 1));
		return;
	}
	float rayStart = max(nearAtmo, 0.0);
	float rayEnd = farAtmo;
	
	float nearGround = 0.0;
	float farGround = 1.0;
	if (RaySphereIntersect(camera.pos, rayDir, planetCenter, groundRadius, nearGround, farGround))
		rayEnd = min(rayEnd, nearGround);
	
	const float mu = dot(rayDir, -sunDir);
	const float stepSize = (rayEnd - rayStart) / atmosphere.steps;
	
	vec3 scat = vec3(0.0, 0.0, 0.0);
	vec3 sigmaSum = vec3(0.0, 0.0, 0.0);
	for (int i = 0; i < atmosphere.steps; ++i)
	{
		const float t = rayStart + (float(i) + 0.5) * stepSize;
		const vec3 samplePos = camera.pos + rayDir * t;
		const float sampleHeight = max(0.0, length(samplePos - planetCenter) - groundRadius);
		
		const vec3 sigmaT = (ScatteringCoefficient(sampleHeight) + AbsorptionCoefficient(sampleHeight));
		sigmaSum += sigmaT * stepSize;
		const vec3 viewT = exp(-sigmaSum);

		vec3 sampleSigmaSum = vec3(0.0, 0.0, 0.0);
		float visibility = 1;
		if (RaySphereIntersect(samplePos, -sunDir, planetCenter, atmosphereRadius, nearAtmo, farAtmo))
		{
			const float sampleToLightStepSize = farAtmo / atmosphere.steps;
			for (int j = 0; j < atmosphere.steps; ++j)
			{
				const float t = (float(j) + 0.5) * sampleToLightStepSize;
				const vec3 lpos = samplePos + -sunDir * t;
				const float lheight = length(lpos - planetCenter) - groundRadius;
				if (lheight < 0.0)
				{
					visibility = 0.0;
					break;
				}	
				const vec3 sigmaT = (ScatteringCoefficient(lheight) + AbsorptionCoefficient(lheight));
				sampleSigmaSum += sigmaT * sampleToLightStepSize;
			}
		}
		const vec3 sampleT = visibility * exp(-sampleSigmaSum); // 논문의 S항
		const vec3 inscatter = 
		(
			rayleighScattering(sampleHeight) * RayleighPhase(mu) + 
			mieScattering(sampleHeight) * MiePhase(mu, 0.8)
		) * stepSize;
		scat += viewT * sampleT * inscatter * atmosphere.sun.w;
	}
	
	imageStore(outImage, pixel, vec4(scat, 1.0));
}