#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform Camera
{
	vec3 pos;
	mat4 view;
	mat4 proj;
	mat4 invView;
	mat4 invProj;
} camera;
layout(set = 1, binding = 0) uniform Atmosphere
{
	vec4 sun; // dir, illuminance
	mat4 sunViewProj;
	ivec2 steps; // view step, sky-view step
	float radius;
	int modeFlags;
} atmosphere;
layout(set = 1, binding = 1, rgba16f) uniform writeonly image2D atmosphereResult;
layout(set = 1, binding = 2) uniform sampler2D depth;
layout(set = 1, binding = 3) uniform sampler2D opaque;
layout(set = 1, binding = 4) uniform sampler2DShadow shadowMap;
layout(set = 1, binding = 5) uniform sampler2D transmittanceLUT;
layout(set = 1, binding = 6) uniform sampler2D skyViewLUT;
layout(set = 1, binding = 7) uniform sampler3D aerialPerspectiveLUT;
layout(set = 1, binding = 8) uniform sampler2D aerialShadowLUT;
layout(set = 1, binding = 9) uniform sampler2D aerialShadowDepth;
layout(set = 1, binding = 10) uniform sampler2D cloudTex;
const float GROUND_RADIUS = 6360 * 1000.0;
const vec3 PLANET_CENTER = vec3(0.0, -GROUND_RADIUS, 0.0);
const float CLOUD_HEIGHT = 2000;
const float CLOUD_THICKNESS = 5000;

vec3 PixelToViewPos(vec2 uv, float z)
{
	vec3 ndc = vec3(uv * 2.0 - 1.0, z);
	ndc.y = -ndc.y;
	vec4 viewPos = camera.invProj * vec4(ndc, 1.0);
	viewPos /= viewPos.w;
	return viewPos.xyz;
}

bool RaySphereIntersect(vec3 rayOrigin, vec3 rayDir, vec3 sphereOrigin, float radius)
{
	vec3 rs = sphereOrigin - rayOrigin;
	float a2 = dot(rs, rs);
	float b = dot(rs, rayDir);
	float c2 = a2 - b * b;
	float r2 = radius * radius;
	if (c2 > r2)
		return false;
	
	float d = sqrt(r2 - c2); // 구 내부 ray길이
	return b + d >= 0.0;
}
bool RaySphereIntersect(vec3 rayOrigin, vec3 rayDir, vec3 sphereOrigin, float radius, out float near, out float far)
{
	vec3 rs = sphereOrigin - rayOrigin;
	float a2 = dot(rs, rs);
	float b = dot(rs, rayDir);
	float c2 = a2 - b * b;
	float r2 = radius * radius;
	if (c2 > r2)
		return false;
	
	float d = sqrt(r2 - c2); // 구 내부 ray길이
	near = b - d;
	far = b + d;
	
	return far >= 0.0;
}

vec3 SkyViewLUT(vec3 rayDir)
{
	const float PI = 3.141592;
	const vec3 camToSun = -atmosphere.sun.xyz;
	const vec3 up = normalize(camera.pos - PLANET_CENTER);
	const vec3 forward = normalize(camToSun - up * dot(camToSun, up));
	const vec3 right = cross(forward, up);
	
	const float latitude = asin(dot(rayDir, up));
	const vec3 horizontal = normalize(rayDir - up * dot(rayDir, up));
	const float longtitude = atan(dot(horizontal, right), dot(horizontal, forward));
	
	vec2 skyUV;
	skyUV.x = longtitude / (2.0 * PI) + 0.5;
	skyUV.y = 1.0 - (0.5 + 0.5 * sign(latitude) * sqrt(abs(latitude) / (PI * 0.5)));
	
	return texture(skyViewLUT, skyUV).xyz;
}

vec3 UpsampledAerialShadow(vec2 uv, float viewZ)
{
	//return texture(aerialShadowLUT, uv).rgb;
	const ivec2 lutSize = textureSize(aerialShadowLUT, 0);
	const vec2 texelPos = lutSize * uv - 0.5;
	const ivec2 base = ivec2(floor(texelPos));
	const vec2 fraction = fract(texelPos);
	
	float weightSum = 0.0;
	vec3 shadowSum = vec3(0.0);
	for (int y = 0; y <= 1; ++y)
	{
		for (int x = 0; x <= 1; ++x)
		{
			const ivec2 offset = ivec2(x, y);
			const ivec2 coord = clamp(base + offset, ivec2(0), lutSize - ivec2(1));
			const vec2 sampleUV = (vec2(coord) + 0.5) / lutSize;
			
			const vec3 shadow = texelFetch(aerialShadowLUT, coord, 0).rgb;
			const float shadowZ = PixelToViewPos(sampleUV, texelFetch(aerialShadowDepth, coord, 0).r).z;
			
			const float weightX = (x == 0) ? 1.0 - fraction.x : fraction.x;
			const float weightY = (y == 0) ? 1.0 - fraction.y : fraction.y;
			const float spatialWeight = weightX * weightY;
			
			float depthDiff = abs(viewZ - shadowZ);
			float weight = exp(-depthDiff * 0.01) * spatialWeight;
			weightSum += weight;
			shadowSum += shadow * weight;
		}
	}

	if (weightSum < 1e-6)
		return vec3(0.0);
	return shadowSum / weightSum;
}

bool RayCloudShellIntersect(vec3 rayOrigin, vec3 rayDir, vec3 center, float innerRadius, float outerRadius, out float tStart, out float tEnd)
{
	float outerNear;
	float outerFar;
	// 구 내부에서 쏘면 near는 음수
	if (!RaySphereIntersect(rayOrigin, rayDir, center, outerRadius, outerNear, outerFar))
		return false;
	
	tStart = max(outerNear, 0.0);
	tEnd = outerFar;
	
	if (tEnd <= tStart)
		return false;
	
	float innerNear;
	float innerFar;
	// 내부구와 충돌x => 우주 or 구름 내부에서 밖을 봄
	if (!RaySphereIntersect(rayOrigin, rayDir, center, innerRadius, innerNear, innerFar))
		return true;
	
	// 구름층 밑
	if (innerNear <= 0.0)
		tStart = innerFar;
	else // 우주 or 구름 내부에서 안을 봄
		tEnd = min(tEnd, innerNear);
	
	return tEnd > tStart;
}

vec3 RenderSun(vec3 worldRayDir, vec3 viewRayDir)
{
	const vec3 toSunDir = -atmosphere.sun.xyz;
	const vec3 sunViewDir = normalize(mat3(camera.view) * toSunDir);
	if (RaySphereIntersect(camera.pos, worldRayDir, PLANET_CENTER, GROUND_RADIUS))
		return vec3(0.0);
	
	const float cosAngle = dot(viewRayDir, sunViewDir);
	const float sunMask = step(cos(radians(0.52)), cosAngle);
	const vec3 sunColor = vec3(atmosphere.sun.w) * sunMask;
	return sunColor;
}

vec4 UpsampledCloud(vec2 uv, float viewZ)
{
	//return texture(cloudTex, uv).;
	const ivec2 texSize = textureSize(cloudTex, 0);
	const vec2 texelPos = texSize * uv - 0.5;
	const ivec2 base = ivec2(floor(texelPos));
	const vec2 fraction = fract(texelPos);
	
	float weightSum = 0.0;
	vec4 cloudSum = vec4(0.0);
	for (int y = 0; y <= 1; ++y)
	{
		for (int x = 0; x <= 1; ++x)
		{
			const ivec2 offset = ivec2(x, y);
			const ivec2 coord = clamp(base + offset, ivec2(0), texSize - ivec2(1));
			const vec2 sampleUV = (vec2(coord) + 0.5) / texSize;
			
			const vec4 cloud = texelFetch(cloudTex, coord, 0);
			const float lowResZ = PixelToViewPos(sampleUV, texelFetch(aerialShadowDepth, coord, 0).r).z;
			
			const float weightX = (x == 0) ? 1.0 - fraction.x : fraction.x;
			const float weightY = (y == 0) ? 1.0 - fraction.y : fraction.y;
			const float spatialWeight = weightX * weightY;
			
			float depthDiff = abs(viewZ - lowResZ);
			float weight = exp(-depthDiff * 0.01) * spatialWeight;
			weightSum += weight;
			cloudSum += cloud * weight;
		}
	}

	if (weightSum < 1e-6)
		return vec4(0.0);
	return cloudSum / weightSum;
}

void main()
{
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(atmosphereResult);
	if (pixel.x >= size.x || pixel.y >= size.y)
		return;
	
	vec2 uv = (vec2(pixel) + 0.5) / vec2(size);
	const vec3 viewRay = PixelToViewPos(uv, 1.0);
	const vec3 rayDir = normalize((camera.invView * vec4(viewRay, 0.0)).xyz);
	
	float nearAtmo = 0.0;
	float farAtmo = 1.0;
	if (!RaySphereIntersect(camera.pos, rayDir, PLANET_CENTER, atmosphere.radius, nearAtmo, farAtmo))
	{
		imageStore(atmosphereResult, pixel, vec4(0, 0, 0, 1)); // 대기와 교차하지 않는 경우(우주)
		return;
	}
	const float z = texture(depth, uv).r;
	const vec3 viewPos = PixelToViewPos(uv, z);
	const float surfaceLength = length(viewPos);
	
	vec3 aerialShadow = vec3(0.0);
	vec4 aerialPerspective = vec4(0.0, 0.0, 0.0, 1.0);
	
	// 0001 AerialPerspective
	// 0010 AerialShadow
	// 0100 Cloud
	if ((atmosphere.modeFlags & 2) == 2)
		aerialShadow = UpsampledAerialShadow(uv, viewPos.z);

	vec3 background = vec3(0.0);
	if (z < 1.0)
	{
		const float lutZ = clamp(surfaceLength / 32000.0, 0.0, 1.0);
		if ((atmosphere.modeFlags & 1) == 1)
			aerialPerspective = texture(aerialPerspectiveLUT, vec3(uv, lutZ));
		
		const vec4 opaqueColor = texture(opaque, uv);
		
		background = opaqueColor.rgb * aerialPerspective.a + (aerialPerspective.rgb - aerialShadow);
	}
	else
	{
		const vec3 skyViewColor = SkyViewLUT(rayDir);
		background = skyViewColor - aerialShadow;
		
		background += RenderSun(rayDir, normalize(viewPos));
	}
	
	const float cloudInnerRadius = GROUND_RADIUS + CLOUD_HEIGHT;
	const float cloudOuterRadius = cloudInnerRadius + CLOUD_THICKNESS;
	vec3 result = background;

	if ((atmosphere.modeFlags & 4) == 4)
	{
		float cloudNear;
		float cloudFar;
		vec3 cloudColor = vec3(0.0);
		if (RayCloudShellIntersect(camera.pos, rayDir, PLANET_CENTER, cloudInnerRadius, cloudOuterRadius, cloudNear, cloudFar))
		{
			const vec4 cloud = UpsampledCloud(uv, viewPos.z);

			vec4 atmosphereToCloud = vec4(0.0, 0.0, 0.0, 1.0);

			if ((atmosphere.modeFlags & 1) == 1)
			{
				const float cloudLutZ = clamp(cloudNear / 32000.0, 0.0, 1.0);
				atmosphereToCloud = texture(aerialPerspectiveLUT, vec3(uv, cloudLutZ));
			}
			// 구름까지 대기의 산란 + (구름까지 대기의 투과율 * 구름의 산란) + 구름의 투과율 * (구름 뒤 산란)
			result = atmosphereToCloud.rgb + (atmosphereToCloud.a * cloud.rgb) +
				cloud.a * (background - atmosphereToCloud.rgb);
		}
	}
	imageStore(atmosphereResult, pixel, vec4(result, 1.0));
}