#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform Camera
{
	vec3 pos;
	mat4 view;
	mat4 proj;
} camera;
layout(set = 1, binding = 0) uniform Atmosphere
{
	vec4 sun; // dir, illuminance
	mat4 sunViewProj;
	ivec2 steps; // view step, sky-view step
	float radius;
} atmosphere;
layout(set = 1, binding = 1, rgba16f) uniform writeonly image2D outImage;
layout(set = 1, binding = 2) uniform sampler2D depth;
layout(set = 1, binding = 3) uniform sampler2D opaque;
layout(set = 1, binding = 4) uniform sampler2DShadow shadowMap;
layout(set = 1, binding = 5) uniform sampler2D transmittanceLUT;
layout(set = 1, binding = 6) uniform sampler2D skyViewLUT;
layout(set = 1, binding = 7) uniform sampler3D aerialPerspectiveLUT;

const float GROUND_RADIUS = 6360 * 1000.0;
const vec3 PLANET_CENTER = vec3(0.0, -GROUND_RADIUS, 0.0);

vec3 PixelToViewPos(vec2 uv, float z)
{
	vec3 ndc = vec3(uv * 2.0 - 1.0, z);
	ndc.y = -ndc.y;
	vec4 viewPos = inverse(camera.proj) * vec4(ndc, 1.0);
	viewPos /= viewPos.w;
	return viewPos.xyz;
}

float Visible(vec3 worldPos)
{
	vec4 sunProjCoord = atmosphere.sunViewProj * vec4(worldPos, 1.0);
	vec2 uv = (sunProjCoord.xy / sunProjCoord.w + 1.0) * 0.5;
	uv.y = 1.0 - uv.y;
	const float z = sunProjCoord.z / sunProjCoord.w;
    if (uv.x < 0.0 || uv.x > 1.0 ||
        uv.y < 0.0 || uv.y > 1.0 ||
        z < 0.0 || z > 1.0)
        return 1.0;
	
	const float shadowing = texture(shadowMap, vec3(uv, z - 0.0005));
	return shadowing;
}

bool RaySphereIntersect(vec3 rayOrigin, vec3 rayDir, vec3 sphereOrigin, float radius, out float near, out float far)
{
	vec3 rs = sphereOrigin - rayOrigin;
	float a2 = dot(rs, rs);
	float b = dot(rs, rayDir);
	float c2 = a2 - b * b;
	float r2 = radius * radius;
	if (c2 > r2)
		return false;
	
	float d = sqrt(r2 - c2); // 구 내부 ray길이
	near = b - d;
	far = b + d;
	
	return far >= 0.0;
}

vec3 SkyViewLUT(vec3 rayDir)
{
	const float PI = 3.141592;
	const vec3 camToSun = -atmosphere.sun.xyz;
	const vec3 up = normalize(camera.pos - PLANET_CENTER);
	const vec3 forward = normalize(camToSun - up * dot(camToSun, up));
	const vec3 right = cross(forward, up);
	
	const float latitude = asin(dot(rayDir, up));
	const vec3 horizontal = normalize(rayDir - up * dot(rayDir, up));
	const float longtitude = atan(dot(horizontal, right), dot(horizontal, forward));
	
	vec2 skyUV;
	skyUV.x = longtitude / (2.0 * PI) + 0.5, 0.1, 0.9;
	skyUV.y = 0.5 - latitude / PI, 0.0, 1;
	
	return texture(skyViewLUT, skyUV).xyz;
}

void main()
{
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(outImage);
	if (pixel.x >= size.x || pixel.y >= size.y)
		return;
	
	vec2 uv = (vec2(pixel) + 0.5) / vec2(size);
	const vec3 viewRay = PixelToViewPos(uv, 1.0);
	const vec3 rayDir = normalize((inverse(camera.view) * vec4(viewRay, 0.0)).xyz);
	
	float nearAtmo = 0.0;
	float farAtmo = 1.0;
	if (!RaySphereIntersect(camera.pos, rayDir, PLANET_CENTER, atmosphere.radius, nearAtmo, farAtmo))
	{
		imageStore(outImage, pixel, vec4(0, 0, 0, 1)); // 대기와 교차하지 않는 경우(우주)
		return;
	}
	
	const float z = texture(depth, uv).r;
	vec3 result = vec3(0.0);
	if (z < 1.0)
	{
		const vec3 opaqueViewPos = PixelToViewPos(uv, z);
		const float opaqueZ = length(opaqueViewPos);
		const float lutZ = clamp(opaqueZ / 32000.0, 0.0, 1.0);
		const vec4 opaqueColor = texture(opaque, uv);
		const vec4 aerialPerspective = texture(aerialPerspectiveLUT, vec3(uv, lutZ));
		
		result = opaqueColor.rgb * aerialPerspective.a + aerialPerspective.rgb;
	}
	else
	{
		const vec3 skyViewColor = SkyViewLUT(rayDir);
		result = skyViewColor;
	}
	imageStore(outImage, pixel, vec4(result, 1.0));
}