#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(set = 0, binding = 0, rgba8) uniform writeonly image2D outImage;
layout(set = 0, binding = 1) uniform Camera
{
	mat4 view;
	mat4 proj;
} camera;

vec3 PixelToViewPos(ivec2 pixel, ivec2 size)
{
	vec2 uv = (vec2(pixel) + 0.5) / vec2(size);
	vec3 ndc = vec3(uv * 2.0 - 1.0, 1.0);
	vec4 viewPos = inverse(camera.proj) * vec4(ndc, 1.0);
	viewPos /= viewPos.w;
	return viewPos.xyz;
}

void main()
{
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(outImage);
	if (pixel.x >= size.x || pixel.y >= size.y)
		return;
	
	imageStore(outImage, pixel, vec4(PixelToViewPos(pixel, size), 1.0));
}