#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform Camera
{
	vec3 pos;
	mat4 view;
	mat4 proj;
	mat4 invView;
	mat4 invProj;
} camera;
layout(set = 1, binding = 0) uniform Setting
{
	uint steps;
	float groundRadius;
	float atmosphereRadius;
	float tiling;
	float extinctionCoefficient;
	float coverage;
	vec2 offset;
	vec4 sun;
} setting;

layout(set = 1, binding = 1, rgba16f) uniform writeonly image2D outImage;
layout(set = 1, binding = 2) uniform sampler3D perlin;
layout(set = 1, binding = 3) uniform sampler2D sceneDepth;
layout(set = 1, binding = 4) uniform sampler2D transmittanceLUT;
const float CLOUD_HEIGHT = 2000;
const float CLOUD_THICKNESS = 5000;
const float PI = 3.14159265;

vec3 PixelToViewPos(vec2 uv, float z)
{
	vec3 ndc = vec3(uv * 2.0 - 1.0, z);
	ndc.y = -ndc.y;
	vec4 viewPos = camera.invProj * vec4(ndc, 1.0);
	viewPos /= viewPos.w;
	return viewPos.xyz;
}

float MiePhase(float mu, float g)
{
	return 3 * (1 - g * g) * (1 + mu * mu) / (8 * 3.141592 * (2 + g * g) * pow(1 + g * g - 2 * g * mu, 3.0/2.0));
}

// 구 내부에서 쏜 경우 near은 음수가 나옴
bool RaySphereIntersect(vec3 rayOrigin, vec3 rayDir, vec3 sphereOrigin, float radius, out float near, out float far)
{
	vec3 rs = sphereOrigin - rayOrigin;
	float a2 = dot(rs, rs);
	float b = dot(rs, rayDir);
	float c2 = a2 - b * b;
	float r2 = radius * radius;
	if (c2 > r2)
		return false;
	
	float d = sqrt(r2 - c2); // 구 내부 ray길이
	near = b - d;
	far = b + d;
	
	return far >= 0.0;
}

// 구름층을 통과하는 구간 갯수를 반환
// 지상에서 밖 [innerFar, outerFar]
// 구름층 내부에서 밖 [0, outerFar]
// 구름층 내부에서 안 [0, innerNear] [innerFar, outerFar] 
// 우주에서 행성 관통X [outerNear, outerFar]
// 우주에서 행성 관통O [outerNear, innerNear]
int RayCloudShellIntersect(vec3 rayOrigin, vec3 rayDir, vec3 center, float innerRadius, float outerRadius, out vec2 segment0, out vec2 segment1)
{
	segment0 = vec2(0.0);
	segment1 = vec2(0.0);

	float outerNear;
	float outerFar;
	if (!RaySphereIntersect(rayOrigin, rayDir, center, outerRadius, outerNear, outerFar))
		return 0; // 우주에서 우주
	outerNear = max(outerNear, 0.0);
	if (outerFar <= outerNear)
		return 0;
	
	float innerNear;
	float innerFar;
	// 내부층과 충돌x => 우주에서 구름 외부층만 보거나, 구름 내부에서 밖을 봄
	if (!RaySphereIntersect(rayOrigin, rayDir, center, innerRadius, innerNear, innerFar))
	{
		segment0 = vec2(outerNear, outerFar);
		return 1;
	}
	
	// 여기서부터 내부구를 볼 수 있는 상태
	float groundNear;
	float groundFar;
	const bool bGroundHit = RaySphereIntersect(rayOrigin, rayDir, center, setting.groundRadius, groundNear, groundFar);
	if (innerNear > 0.0)
	{
		segment0 = vec2(outerNear, innerNear);
		if (bGroundHit && groundNear > 0.0) // 구름층/우주에서 땅을 보는 상태
			return 1;
		segment1 = vec2(innerFar, outerFar);
		return 2;
	}
	
	if (bGroundHit) // 지상에서 땅
		return 0;
	
	segment0 = vec2(innerFar, outerFar); // 지상에서 밖
	return 1;
}

float Remap(float value, float originalMin, float originalMax, float newMin, float newMax)
{
	return newMin + ((value - originalMin) / (originalMax - originalMin)) * (newMax - newMin);
}

float GetDensity(float cloudInnerRadius, float cloudOuterRadius, vec3 samplePos)
{
	const vec3 PLANET_CENTER = vec3(0.0, -setting.groundRadius, 0.0);
	const float sampleRadius = length(samplePos - PLANET_CENTER);
	const float heightRatio = clamp((sampleRadius - cloudInnerRadius) / CLOUD_THICKNESS, 0.0, 1.0);
	
	const float bottomFade = smoothstep(0.0, 0.15, heightRatio);
	const float topFade = 1.0 - smoothstep(0.85, 1.0, heightRatio);
	const float heightMask = bottomFade * topFade;
	
	const vec3 uvw = samplePos / setting.tiling;
	const vec4 noise = texture(perlin, uvw + vec3(setting.offset.x, 0.0, setting.offset.y));
	const float wfbm = noise.g * 0.625 + noise.b * 0.125 + noise.a * 0.25;
	float cloud = Remap(noise.r, wfbm, 1.0, 0.0, 1.0);
	cloud = clamp(Remap(cloud, 1.0 - setting.coverage, 1.0, 0.0, 1.0), 0.0, 1.0);

	return cloud * heightMask;
}

vec3 CloudToSunTransmittance(vec3 a, vec3 b, float distance, uint steps, float cloudInnerRadius, float cloudOuterRadius)
{
	const float stepSize = distance / steps;
	const vec3 dir = (b - a) / distance;
	
	vec3 sigmaSum = vec3(0.0, 0.0, 0.0);
	for (uint i = 0; i < steps; ++i)
	{
		const vec3 samplePos = a + dir * stepSize * (i + 0.5);
		const float density = GetDensity(cloudInnerRadius, cloudOuterRadius, samplePos);
		
		sigmaSum += density * setting.extinctionCoefficient * stepSize;
	}
	return exp(-sigmaSum);
}

vec2 GetTransmittanceUV(vec3 samplePos, vec3 dir)
{
	const vec3 PLANET_CENTER = vec3(0.0, -setting.groundRadius, 0.0);
	
	const float sampleLength = length(samplePos - PLANET_CENTER);
	const float height = sampleLength - setting.groundRadius;
	const vec3 up = (samplePos - PLANET_CENTER) / sampleLength;
	const float mu = dot(up, dir);
	
	const float r = height + setting.groundRadius;
	// 지평선에서 대기까지의 거리 H
	const float H = sqrt(setting.atmosphereRadius * setting.atmosphereRadius - setting.groundRadius * setting.groundRadius);
	// 지평선 거리 rho
	const float rho = sqrt(r * r - setting.groundRadius * setting.groundRadius);
	
	const float dMin = setting.atmosphereRadius - r; // 머리 위의 대기까지의 거리
	const float dMax = rho + H; // 지평선 너머의 대기까지의 거리
	float d = -r * mu + sqrt(r * r * (mu * mu - 1) + setting.atmosphereRadius * setting.atmosphereRadius); // 샘플에서 ray방향으로의 대기권까지의 거리
	d = max(d, 0.0);
	
	float u = (d - dMin) / (dMax - dMin); // 0(머리위) ~ 1(지평선)
	float v = rho / H; // 그냥 높이 비율 대신 제곱근 비율로 바뀐거
	v = 1.0 - v;
	return vec2(u, v);
}

vec3 TransmittanceUsingLUT(vec3 samplePos, vec3 dir)
{
	const ivec2 size = textureSize(transmittanceLUT, 0);
	vec2 uv = GetTransmittanceUV(samplePos, dir);
	uv = (vec2(0.5) + uv * (size - vec2(1.0))) / size;
	
	return texture(transmittanceLUT, uv).xyz;
}

void SegmentTransmittance(
	vec3 rayOrigin, 
	vec3 rayDir, 
	vec2 segment, 
	float steps, 
	float cloudInner, 
	float cloudOuter, 
	vec3 sunDir, 
	float phase,
	inout vec3 inScattering,
	inout float transmittance)
{
	const vec3 PLANET_CENTER = vec3(0.0, -setting.groundRadius, 0.0);
	
	const float segmentLength = segment.y - segment.x;
	const uint segmentSteps = max(1u, uint(ceil(segmentLength  / steps)));
	
	const float stepSize = segmentLength / float(segmentSteps);
	
	for (uint i = 0; i < segmentSteps; ++i)
	{
		if (transmittance <= 0.01)
            break;
		
		const float t = segment.x + stepSize * (i + 0.5);
		const vec3 samplePos = rayOrigin + rayDir * t;
		const float density = GetDensity(cloudInner, cloudOuter, samplePos);
		if (density <= 0.0001)
			continue;
		
		vec3 lightViewT = vec3(1.0);
		float groundNear;
		float groundFar;
		
		if (RaySphereIntersect(samplePos, -sunDir, PLANET_CENTER, setting.groundRadius, groundNear, groundFar))
			lightViewT = vec3(0.0);
		else
		{
			float lightNear;
			float lightFar;
			if (RaySphereIntersect(samplePos, -sunDir, PLANET_CENTER, cloudOuter, lightNear, lightFar))
			{
				lightViewT = CloudToSunTransmittance(samplePos, samplePos - sunDir * lightFar, lightFar, 10, cloudInner, cloudOuter);
				lightViewT *= TransmittanceUsingLUT(samplePos - sunDir * lightFar, -sunDir);
			}
		}
		
		const float sigma = density * stepSize * setting.extinctionCoefficient;
		const float stepTransmittance = exp(-sigma);
		inScattering += (1.0 - stepTransmittance) * transmittance * (lightViewT * phase * setting.sun.w);
		transmittance *= stepTransmittance;
	}
}	

void main()
{
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(outImage);
	if (pixel.x >= size.x || pixel.y >= size.y)
		return;
	vec2 uv = (vec2(pixel) + 0.5) / vec2(size);

	vec4 p = texture(perlin, vec3(uv, 0.0));
	// if (uv.x < 0.25)
		// imageStore(outImage, pixel, vec4(vec3(p.r), 1.0));
	// else if (uv.x < 0.5)
		// imageStore(outImage, pixel, vec4(vec3(p.g), 1.0));
	// else if (uv.x < 0.75)
		// imageStore(outImage, pixel, vec4(vec3(p.b), 1.0));
	// else
		// imageStore(outImage, pixel, vec4(vec3(p.a), 1.0));
	// return;
	
	// float wfbm = p.g * 0.625 + p.b * 0.125 + p.a * 0.25;
	// float cloud = Remap(p.r, wfbm, 1.0, 0.0, 1.0);
	// imageStore(outImage, pixel, vec4(vec3(cloud), 1.0));
	// return;
	
	const vec3 viewRay = PixelToViewPos(uv, 1.0);
	const vec3 rayDir = normalize((camera.invView * vec4(viewRay, 0.0)).xyz);
	const float cloudInnerRadius = setting.groundRadius + CLOUD_HEIGHT;
	const float cloudOuterRadius = cloudInnerRadius + CLOUD_THICKNESS;
	const vec3 PLANET_CENTER = vec3(0.0, -setting.groundRadius, 0.0);
	
	vec2 cloudSegment0;
	vec2 cloudSegment1;
	int cloudSegmentCount = 
		RayCloudShellIntersect(camera.pos, rayDir, PLANET_CENTER, cloudInnerRadius, cloudOuterRadius, cloudSegment0, cloudSegment1);
	if (cloudSegmentCount == 0)
	{
		imageStore(outImage, pixel, vec4(0.0, 0.0, 0.0, 1.0));
		return;
	}

	const float z = texture(sceneDepth, uv).r;
	const vec3 viewPos = PixelToViewPos(uv, z);
	const float sceneDistance = length(viewPos);
	if (z < 1.0)
	{
		cloudSegmentCount = 1;
		cloudSegment0.y = min(cloudSegment0.y, sceneDistance);
	}
	
	const vec3 sunDir = setting.sun.xyz;
	const float mu = dot(rayDir, -sunDir);
	const float phase = mix(MiePhase(mu, 0.8), 1.0 / (4.0 * PI), 0.3);

	vec3 inScattering = vec3(0.0);
	float transmittance = 1.0;
	if (cloudSegmentCount == 1)
	{
		SegmentTransmittance(
			camera.pos, rayDir, cloudSegment0, setting.steps, 
			cloudInnerRadius, cloudOuterRadius, sunDir, phase, 
			inScattering, transmittance);
	}
	else if (cloudSegmentCount == 2)
	{
		SegmentTransmittance(
			camera.pos, rayDir, cloudSegment0, setting.steps / 2, 
			cloudInnerRadius, cloudOuterRadius, sunDir, phase, 
			inScattering, transmittance);
		SegmentTransmittance(
			camera.pos, rayDir, cloudSegment1, setting.steps / 2, 
			cloudInnerRadius, cloudOuterRadius, sunDir, phase, 
			inScattering, transmittance);
	}
	
	imageStore(outImage, pixel, vec4(inScattering, transmittance));
}