#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 1, binding = 0, r32f) uniform writeonly image2D lowResDepth;
layout(set = 1, binding = 1) uniform sampler2D sceneDepth;
void main()
{
	const ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
	
	const ivec2 lowSize = imageSize(lowResDepth);
	if (pixel.x >= lowSize.x || pixel.y >= lowSize.y)
		return;
	vec2 uv = (vec2(pixel) + 0.5) / vec2(lowSize);
	
	imageStore(lowResDepth, pixel, texture(sceneDepth, uv));
}